development:
  icecondos_db: icecondos_development
  icecondos_db_connection:
    adapter: mysql2
    encoding: utf8
    database: icecondos_development
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
  icecondos_url: http://icecondos.dev
  api_token: ZuB2nB24GTyWsyuPVRwMaZmi
  crm_call_token: MiB2nB24GTyWsyuPVRwMaZOk

staging:
  icecondos_db: icecondos_staging
  icecondos_db_connection:
    adapter: mysql2
    encoding: utf8
    database: icecondos_staging
    pool: 5
    username: rails
    password: rails
  icecondos_url: http://beta.icecondos.ca
  api_token: ZuB2nB24GTyWsyuPVRwMaZmi
  crm_call_token: MiB2nB24GTyWsyuPVRwMaZOk

production:
  icecondos_db: icecondos_production
  icecondos_db_connection:
    adapter: mysql2
    encoding: utf8
    database: icecondos_production
    pool: 5
    username: rails
    password: rails_icecondos
  icecondos_url: http://icecondos.com
  api_token: ZuB2nB24GTyWsyuPVRwMaZmi
  crm_call_token: MiB2nB24GTyWsyuPVRwMaZOk
