development:
  access_key_id: AKIAJHTFIDI5EXOYX5YQ
  secret_access_key: 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

staging:
  access_key_id: AKIAJHTFIDI5EXOYX5YQ
  secret_access_key: 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

production:
  access_key_id: AKIAJHTFIDI5EXOYX5YQ
  secret_access_key: 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